package com.reactive.flink.model;

import java.io.Serializable;

/**
 * Counter event received from Kafka.
 *
 * Business IDs:
 * - requestId: Correlation ID for this request (generated by gateway)
 * - customerId: Customer/tenant ID for multi-tenancy
 * - eventId: Unique event ID
 * - sessionId: Counter instance ID
 *
 * Note: OpenTelemetry trace propagation is handled automatically by the OTel agent
 * via W3C traceparent headers in Kafka. No need to manually propagate trace IDs.
 */
public class CounterEvent implements Serializable {
    private static final long serialVersionUID = 3L;

    private String requestId;      // Correlation ID for this request
    private String customerId;     // Customer/tenant ID for multi-tenancy
    private String eventId;        // Unique event ID
    private String sessionId;      // Counter instance ID
    private String action;         // "increment", "decrement", "set"
    private int value;
    private long timestamp;
    private EventTiming timing;
    private long deserializedAt;

    public CounterEvent() {
    }

    public CounterEvent(String sessionId, String action, int value) {
        this.sessionId = sessionId;
        this.action = action;
        this.value = value;
        this.timestamp = System.currentTimeMillis();
    }

    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public String getEventId() {
        return eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        this.value = value;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public EventTiming getTiming() {
        return timing;
    }

    public void setTiming(EventTiming timing) {
        this.timing = timing;
    }

    public long getDeserializedAt() {
        return deserializedAt;
    }

    public void setDeserializedAt(long deserializedAt) {
        this.deserializedAt = deserializedAt;
    }

    @Override
    public String toString() {
        return "CounterEvent{" +
                "requestId='" + requestId + '\'' +
                ", customerId='" + customerId + '\'' +
                ", sessionId='" + sessionId + '\'' +
                ", action='" + action + '\'' +
                ", value=" + value +
                ", eventId='" + eventId + '\'' +
                '}';
    }
}
