package com.reactive.flink.model;

import com.reactive.platform.observe.TracedMessage;

import static com.reactive.platform.Opt.or;

/**
 * Counter event received from Kafka.
 *
 * Business IDs:
 * - requestId: Correlation ID for this request (generated by gateway)
 * - customerId: Customer/tenant ID for multi-tenancy
 * - eventId: Unique event ID
 * - sessionId: Counter instance ID
 *
 * Immutable record with compact constructor for boundary normalization.
 * Implements TracedMessage for automatic span attribute extraction
 * and trace context propagation.
 */
public record CounterEvent(
        String requestId,
        String customerId,
        String eventId,
        String sessionId,
        String action,
        int value,
        long timestamp,
        EventTiming timing,
        long deserializedAt,
        String traceparent,
        String tracestate
) implements TracedMessage {
    /**
     * Compact constructor normalizes all fields at construction.
     * BOUNDARY: Jackson deserialization may provide nulls.
     */
    public CounterEvent {
        requestId = or(requestId, "");
        customerId = or(customerId, "");
        eventId = or(eventId, "");
        sessionId = or(sessionId, "");
        action = or(action, "increment");
        timing = EventTiming.from(timing);
        traceparent = or(traceparent, "");
        tracestate = or(tracestate, "");
    }

    /**
     * Convenience constructor for simple event creation.
     */
    public CounterEvent(String sessionId, String action, int value) {
        this("", "", "", sessionId, action, value, System.currentTimeMillis(),
                EventTiming.empty(), 0, "", "");
    }

    public CounterEvent withDeserializedAt(long t) {
        return new CounterEvent(requestId, customerId, eventId, sessionId, action,
                value, timestamp, timing, t, traceparent, tracestate);
    }

    public CounterEvent withTraceContext(String traceparent, String tracestate) {
        return new CounterEvent(requestId, customerId, eventId, sessionId, action,
                value, timestamp, timing, deserializedAt, traceparent, tracestate);
    }

    @Override
    public String toString() {
        return "CounterEvent{" +
                "requestId='" + requestId + '\'' +
                ", customerId='" + customerId + '\'' +
                ", sessionId='" + sessionId + '\'' +
                ", action='" + action + '\'' +
                ", value=" + value +
                ", eventId='" + eventId + '\'' +
                '}';
    }
}
